name: Build and Deploy Workflow

on:
  workflow_dispatch:
    inputs:
      DOCKERFILE_PATH:
        description: Path to the Dockerfile
        required: false
        default: "./Dockerfile"
      APP_NAME:
        description: Application Name
        required: true
        default: "java-web-app"
      CONTEXT_PATH:
        description: Docker build context
        required: false
        default: "./"
      CODE_REPO:
        description: Code repository URL
        required: true
        default: "madilshahzad/web-app"
      HELM_RELEASE_NAME:
        description: Helm release name
        required: true
        default: "java-web-app"
      HELM_CHART_PATH:
        description: Path to the Helm chart directory
        required: true
        default: "java-web-app"
      EKS_CLUSTER_NAME:
        description: EKS Cluster Name
        required: true
        default: "eks-cluster"

permissions:
  id-token: write
  contents: read

jobs:
  maven-build:
    uses: madilshahzad/reusable-template/.github/workflows/build-maven.yml@main
    with:
      CODE_REPO: ${{ github.event.inputs.CODE_REPO }}

  build-and-push:
    needs: maven-build
    uses: madilshahzad/reusable-template/.github/workflows/build-push.yml@main
    with:
      DOCKERFILE_PATH: ${{ github.event.inputs.DOCKERFILE_PATH }}
      APP_NAME: ${{ github.event.inputs.APP_NAME }}
      CONTEXT_PATH: ${{ github.event.inputs.CONTEXT_PATH }}
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ROLE_NAME: ${{ secrets.ROLE_NAME }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Get Image Tag from Build and Push Job
        run: echo "Using Image Tag: ${{ needs.build-and-push.outputs.IMAGE_TAG_DEPLOY }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHub-Actions
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update Kubeconfig for EKS
        run: |
          aws eks update-kubeconfig \
            --region ${{ secrets.AWS_REGION }} \
            --name ${{ github.event.inputs.EKS_CLUSTER_NAME }} \
            --role-arn arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHub-Actions \
            --alias eks-cluster

      - name: Verify Cluster
        run: kubectl get nodes

      - name: Clone Helm Chart Repository
        run: |
          git clone https://github.com/madilshahzad/helm_charts.git
          cd helm_charts
          echo "Cloned Helm Chart Repository"

      - name: Navigate to Helm Chart Directory
        working-directory: helm_charts/${{ github.event.inputs.HELM_CHART_PATH }}
        run: |
          echo "Navigated to Helm Chart Directory"

      - name: Deploy Using Helm
        working-directory: helm_charts/${{ github.event.inputs.HELM_CHART_PATH }}
        run: |
          helm upgrade --install ${{ github.event.inputs.HELM_RELEASE_NAME }} ./ \
            --set image.repository=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }} \
            --set image.tag=${{ needs.build-and-push.outputs.IMAGE_TAG_DEPLOY }}
