name: Build and Deploy Workflow

on:
  workflow_dispatch:
    inputs:
      DOCKERFILE_PATH:
        description: Path to the Dockerfile
        required: false
        default: "./Dockerfile"
      APP_NAME:
        description: Application Name
        required: true
      CONTEXT_PATH:
        description: Docker build context
        required: false
        default: "./"

jobs:
  build_and_push:
    uses: madilshahzad/reusable-template/.github/workflows/build-push.yml@main
    with:
      DOCKERFILE_PATH: ${{ github.event.inputs.DOCKERFILE_PATH }}
      APP_NAME: ${{ github.event.inputs.APP_NAME }}
      CONTEXT_PATH: ${{ github.event.inputs.CONTEXT_PATH }}
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ROLE_NAME: ${{ secrets.ROLE_NAME }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Get Output from Build and Push Job
        run: "echo 'Image Tag: ${{ needs.build_and_push.outputs.IMAGE_TAG_DEPLOY }}'"

      - name: Deploy Placeholder
        run: |
          echo "Deploying application with image tag:"
          echo "${{ needs.build_and_push.outputs.IMAGE_TAG_DEPLOY }}"
