name: Build and Deploy Workflow

on:
  workflow_dispatch:
    inputs:
      DOCKERFILE_PATH:
        description: Path to the Dockerfile
        required: false
        default: "./Dockerfile"
      APP_NAME:
        description: Application Name
        required: true
      CONTEXT_PATH:
        description: Docker build context
        required: false
        default: "./"
      CODE_REPO:
        description: Code repository URL
        required: true
      HELM_RELEASE_NAME:
        description: Helm release name
        required: true
      HELM_CHART_PATH:
        description: Path to the Helm chart directory
        required: true
      KUBE_CONFIG_PATH:
        description: Kubernetes config path
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  maven-build:
    uses: madilshahzad/reusable-template/.github/workflows/build-maven.yml@main
    with:
      CODE_REPO: ${{ github.event.inputs.CODE_REPO }}

  build-and-push:
    needs: maven-build
    uses: madilshahzad/reusable-template/.github/workflows/build-push.yml@main
    with:
      DOCKERFILE_PATH: ${{ github.event.inputs.DOCKERFILE_PATH }}
      APP_NAME: ${{ github.event.inputs.APP_NAME }}
      CONTEXT_PATH: ${{ github.event.inputs.CONTEXT_PATH }}
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ROLE_NAME: ${{ secrets.ROLE_NAME }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Get Image Tag from Build and Push Job
        run: echo "Image Tag: ${{ needs.build-and-push.outputs.IMAGE_TAG_DEPLOY }}"

      - name: Set Up Kubernetes Config
        run: |
          echo "${{ secrets.KUBE_CONFIG_PATH }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy Using Helm
        run: |
          helm upgrade --install ${{ github.event.inputs.HELM_RELEASE_NAME }} \
            ${{ github.event.inputs.HELM_CHART_PATH }} \
            --set image.repository=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }} \
            --set image.tag=${{ needs.build-and-push.outputs.IMAGE_TAG_DEPLOY }} \
            --kubeconfig ~/.kube/config
